### ISSUE TITLE
Team Doudna Code Review

### ISSUE THREAD

**Issue by lizchoi0918** [oghomiep/EEP153Project4#16]
Hi, overall really great code and I liked how you organized the file into three parts. It made it easy for me to follow individual deliverables.
Couple of suggestions I could give are:
1) Legends missing in Engel Curves graph. This makes it hard which goods are correlated to which line in the graph. 
2) I think a little bit more explanation on the graphs overall might be helpful in making the content more easy to follow.

**Comment by oghomiep** [comment]
Thanks for the feedback! Fixed (1) but was unclear about (2). Most of the code is borrowed from prof Ligon, whose explanations I thought were adequate.
